import type { CardData } from './types';

export const cardData: CardData[] = [
  {
    id: 1,
    type: 'image',
    src: '/images/sample-image.jpg',
    alt: 'A sample fantasy landscape',
    effects: ['border', 'interactive-sparkle', 'glow'],
    title: 'Whispering Peaks',
    description: 'A mystical mountain range that hums with ancient energy.',
    rarity: 'legendary',
    edition: 'Founders Pack',
    date: '2025-Q4',
  },
  {
    id: 2,
    type: 'video',
    src: '/videos/sample-video.mp4',
    alt: 'A sample abstract video',
    effects: ['border', 'sparkle', 'glow'],
    title: 'Orb of Chaos',
    description: 'A swirling vortex of unpredictable magical power.',
    rarity: 'rare',
    edition: 'Core Set',
    date: '2025-Q2',
  },
  {
    id: 3,
    type: 'embed',
    src: 'https://chzzk.naver.com/embed/clip/kpeDI5usC7',
    alt: 'Chzzk Video Clip',
    effects: ['border', 'glow'],
    title: 'Epic Moment',
    description: 'An amazing play from a Chzzk streamer.',
    rarity: 'epic',
    edition: 'Live Clips',
    date: '2025-Q3',
  },
];
